Repository myConsciousness/freezer, pull requests merged in 2022-08, with the labels that each got.

#2 fix: fixed exit code
  lib/src/build_runner.dart
Labels: bug

#3 fix: renamed entry file name
  CHANGELOG.md
  bin/main.dart
  pubspec.yaml
Labels: bug

#5 [Scheduled] `dart pub upgrade --null-safety`
  pubspec.yaml
Labels: GitHub Actions

#24 feat: fixed for the issue (#7)
  CHANGELOG.md
  README.md
  design/sample/shop.freezer.json
  example/README.md
  lib/src/model/parameter.dart
  pubspec.yaml
  test/freezer_test.dart
  test/src/freezed_object_parser_test.dart
Labels: enhancement

#26 [Scheduled] `dart pub upgrade --null-safety`
  pubspec.lock
Labels: GitHub Actions

#27 [Scheduled] `dart pub upgrade --null-safety`
  pubspec.lock
Labels: GitHub Actions

#32 feat: fixed for the issue (#8)
  CHANGELOG.md
  README.md
  design/sample/common/common.freezer.json
  design/sample/shop.freezer.json
  lib/src/freezed_object_parser.dart
  lib/src/freezer.dart
  lib/src/model/dart_object.dart
  lib/src/model/freezed_parameter.dart
  lib/src/model/import_package.dart
  lib/src/model/reference.dart
  lib/src/resource_builder.dart
  pubspec.yaml
  test/src/freezed_object_parser_test.dart
  test/src/freezed_resource_test.dart
Labels: enhancement

#35 feat: fixed for the issue (#34)
  CHANGELOG.md
  README.md
  design/sample/shop.freezer.json
  lib/src/model/freezed_parameter.dart
  lib/src/policy/freezer_identifier.dart
  pubspec.yaml
  test/src/freezer_identifier_test.dart
Labels: enhancement

#38 fix: fixed for the issue (#36)
  CHANGELOG.md
  README.md
  lib/src/model/enum_element.dart
  lib/src/resource_builder.dart
  pubspec.yaml
Labels: enhancement

#39 feat: fixed for the issue (#37)
  CHANGELOG.md
  README.md
  design/sample/shop.freezer.json
  lib/src/model/dart_object.dart
  lib/src/policy/freezer_identifier.dart
  lib/src/resource_builder.dart
Labels: enhancement

#42 feat: allow package reference
  CHANGELOG.md
  lib/src/model/import_package.dart
  lib/src/resource_builder.dart
  pubspec.yaml
Labels: enhancement
